FROM node:14

WORKDIR /app

COPY package*.json ./
RUN npm install --force

COPY . .

RUN npm run build --force

FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
